backend:
  name: github
  repo: brown-ccv/mmp
media_folder: public/images
i18n:
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  structure: multiple_folders
  # Required - a list of locales to show in the editor UI
  locales: [en, es, pt]
  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
